apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubetrainer.fullname" . }}
data:
  CONSUMER_MODE: {{ .Values.configuration.CONSUMER_MODE | quote }}
  DB_DSN: {{ .Values.configuration.DB_DSN | quote }}
  REDIS_DSN: {{ .Values.configuration.REDIS_DSN | quote }}
  REDIS_STREAMNAME: {{ .Values.configuration.REDIS_STREAMNAME | quote }}
  REDIS_STREAMGROUP: {{ .Values.configuration.REDIS_STREAMGROUP | quote }}
  REDIS_MAXSTREAMLENGTH: {{ .Values.configuration.REDIS_MAXSTREAMLENGTH | quote }}
  PRODUCER_DATA_SIZE_BYTES: {{ printf "%.0f" .Values.configuration.PRODUCER_DATA_SIZE_BYTES }}
